### ISSUE TITLE
Change to github.com host only

### ISSUE THREAD

**Issue by kdszafranski** [PrimeAcademy/software-installs#7]
https://github.com/PrimeAcademy/software-installs/blob/c40e6971bce62984d190c05680dc9957ef6a5b1f/git-ssh.sh#L32

**Comment by kdszafranski** [comment]
https://github.com/PrimeAcademy/curriculum-syllabus-master/issues/549

**Comment by eschwartz** [comment]
So @kdszafranski -- having `Host *` breaks your SSH config for other keys/domains?

**Comment by eschwartz** [comment]
FWIW, I'm not seeing this same issue -- I have a minecraft server running on AWS, was able to connect to it still after running this script

![image](https://user-images.githubusercontent.com/1153371/110389861-bd6dbf00-802a-11eb-85e8-73e05cda8d9d.png)

**Comment by kdszafranski** [comment]
well, one of them needs to be specific. I don't know why we'd choose to co-opt * when we can be specific
